import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
// import { ReactComponent as News } from 'icons/news.svg';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        <title>Hooman Studio CMS app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link 
          rel="preload"
          href="/fonts/SupremeLL-Medium.otf"
          as="font"
          crossOrigin=""
        />

      </Head>

      <Header />
      {/* <div className={styles.navContainer}>
        <nav>
          <ul>
            <li>
              <img rel="icon" src="/icons/news.svg" ></img>
              <a>News and articles</a>
            </li>
            <li>
              <a>Lawyers</a>
            </li>
            <li>
              <a>Webinars</a>
            </li>
            <li>
              <a>Investments</a>
            </li>
            <li>
              <a>Closed Investments</a>
            </li>
          </ul>

          <hr/>

          <ul>
            <li>
              <a>Read</a>
            </li>
            <li>
              <a>Watch</a>
            </li>
            <li>
              <a>Listen</a>
            </li>
            <li>
              <a>Fundamental</a>
            </li>
            <li>
              <a>Authors</a>
            </li>
            <li>
              <a>Categories</a>
            </li>
          </ul>
        </nav>
      </div> */}


      <main className={styles.mainContainer}>
        <div className={styles.saveContainer}>
          <div className={styles.discard}>
            <a>Discard</a>
          </div>
          <div className={styles.save}>
            <a>Save</a>
          </div>
        </div>

      </main>

    </div>
  )
}
